linux:
  hosts:
    aws-ubuntu:
      ansible_host: 3.224.96.97
      ansible_user: ubuntu
  vars:
    ansible_ssh_private_key_file: /home/cybersmith/ceg2410-aws-vm.pem

windows:
  hosts:

allsystems:
  children:
    linux:
    windows:
